homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  whitelist_external_dirs:
  - /config
  - /ssl
#
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
shell_command: !include shell_commands.yaml
history_graph: !include historygraphs.yaml
notify: !include notifications.yaml
rest_command: !include rest_commands.yaml
rss_feed_template: !include rss_feed.yaml
weblink: !include weblinks.yaml
#
frontend:
#
lovelace:
  mode: yaml
#
http:
  api_password: !secret http_password
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 3
  trusted_networks:
  - !secret trustednet
  - 172.30.32.0/24
#
config:
#
recorder:
  db_url: !secret dburl
  purge_keep_days: 31
  purge_interval: 7
#
updater:
  reporting: false
#
discovery:
  ignore:
  - plex_mediaserver
  - tellstick
#
conversation:
#
history:
#
logbook:
  exclude:
    domains:
    - automation
    entities:
    - sensor.time
    - sensor.date
#
map:
#
sun:
#
wake_on_lan:
#
media_player:
  - platform: plex
    scan_interval: 3
#
media_extractor:
#
device_tracker:
  - platform: nmap_tracker
    home_interval: 3
    interval_seconds: 20
    hosts: !secret devicetracksniff
#
person:
#
lametric:
  client_id: !secret lametricclientid
  client_secret: !secret lametricclientsecret
#
tellduslive:
#
system_health:
#