- name: pushbullet
  platform: pushbullet
  api_key: !secret pushbulletapi
#
- platform: lametric
  name: lametricsovrum
  lifetime: 60
  icon: a7956
  cycles: 3
#
- platform: file
  name: lametric_media_play_notify
  filename: /config/shell_coms/lametric_media_playing/lametric_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_privatmobil_notify
  filename: /config/shell_coms/lametric_notifications/lametric_privatmobil_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_jobbmobil_notify
  filename: /config/shell_coms/lametric_notifications/lametric_jobbmobil_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_temp_framsidan_notify
  filename: /config/shell_coms/lametric_notifications/lametric_temp_framsidan_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_temp_yr_notify
  filename: /config/shell_coms/lametric_notifications/lametric_temp_yr_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_temp_smhi_notify
  filename: /config/shell_coms/lametric_notifications/lametric_temp_smhi_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_vind_yr_notify
  filename: /config/shell_coms/lametric_notifications/lametric_vind_yr_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_vind_smhi_notify
  filename: /config/shell_coms/lametric_notifications/lametric_vind_smhi_variable.txt
  timestamp: false
#
- platform: file
  name: lametric_svullo_anvant_notify
  filename: /config/shell_coms/lametric_notifications/lametric_svullo_anvant_variable.txt
  timestamp: false
#