#
#
#

# MQTT
- alias: "battery_warning_fyrtur_bedroom"
  id: "Batterivarning Fyrtur sovrum"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.fyrtur_block_out_roller_blind_battery_level
      below: 40
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Batteri slut, ladda"
        message: "Rullgardinen i sovrummet {{ states('sensor.fyrtur_block_out_roller_blind_battery_level') }}% kvar"
#
- alias: "battery_warning_garagelock"
  id: "Batterivarning garagelås"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.garagelas_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Batteri slut"
        message: "Garagelås magnetkontakt har {{ states('sensor.garagelas_battery_level') }}% kvar"
#
- alias: "battery_warning_guest_room_dimmer_switch"
  id: "Batterivarning gästrum dimmerfjärr"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.guest_room_dimmer_switch_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Batteri slut"
        message: "Gästrummets dimmerfjärr har {{ states('sensor.guest_room_dimmer_switch_battery') }}% kvar"
#
- alias: "battery_warning_hall_fjarr"
  id: "Batterivarning hall fjärr"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.hall_fjarr_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "fjärrkontroll i hallen {{ states('sensor.hall_fjarr_battery') }}% kvar"
#
- alias: "battery_warning_hall_door_magnet"
  id: "Batterivarning Hall Dörrmagnet"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.hall_door_magnet_switch_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Batteri slut"
        message: "Hall ytterdörr magnetkontakt har {{ states('sensor.hall_door_magnet_switch_battery_level') }}% kvar"
#
- alias: "battery_warning_hall_garderob_door_magnet"
  id: "Batterivarning Hall Garderob Dörrmagnet"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.hall_garderob_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Batteri slut"
        message: "Hall garderob magnetkontakt har {{ states('sensor.hall_garderob_battery_level') }}% kvar"
#
- alias: "battery_warning_magnet_cold_storage"
  id: "Batterivarning magnet matkällare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.kallare_matkallare_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Magnetsensor till matkällardörr {{ states('sensor.kallare_matkallare_battery_level') }}% kvar"
#
- alias: "battery_warning_magnet_liquor_cabinet"
  id: "Batterivarning magnet spritskåp"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.kok_spritskap_dorr_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Magnetsensor till spritskåp har {{ states('sensor.kok_spritskap_dorr_battery') }}% kvar"
#
- alias: "battery_warning_matsal_ensis_ljud"
  id: "Batterivarning Matsal Ensis Ljud"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.matsal_ensis_ljud_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Fjärrkontrollen i matsalen för ljud och Ensis {{ states('sensor.matsal_ensis_ljud_battery_level') }}% kvar"
#
- alias: "battery_warning_motion_hall"
  id: "Batterivarning Rörelse Hall"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_hall_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor i halltaket sovrum har {{ states('sensor.motion_hall_battery_level') }}% kvar"
#
- alias: "battery_warning_motion_hall_entre"
  id: "Batterivarning Rörelse Hall Entre"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_hall_entre_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor i halltaket Entre har {{ states('sensor.motion_hall_entre_battery') }}% kvar"
#
- alias: "battery_warning_motion_kitchen_roof"
  id: "Batterivarning Rörelse kökstak"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_kok_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensorn i kökstaket har {{ states('sensor.motion_kok_battery_level') }}% kvar, vill ha 2st AAA"
#
- alias: "battery_warning_motion_dining_room"
  id: "Batterivarning rörelse matsal"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_matsal_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor i matsalstaket har {{ states('sensor.motion_matsal_battery_level') }}% kvar, 2st AAA"
#
- alias: "battery_warning_motion_hobbyrum_speldator"
  id: "Batterivarning rörelse Hobbyrum Speldator"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_hobbyrum_speldator_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor i hobbyrum vid speldator har {{ states('sensor.motion_hobbyrum_speldator_battery_level') }}% kvar"
#
- alias: "battery_warning_motion_outside_entrance"
  id: "Batterivarning rörelse ute entre"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_outside_entrance_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor ute vid entren har {{ states('sensor.motion_outside_entrance_battery') }}% kvar"
#
- alias: "battery_warning_motion_outside_garage"
  id: "Batterivarning rörelse ute Garaget"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_outside_garage_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor ute vid garaget har {{ states('sensor.motion_outside_garage_battery') }}% kvar"
#
- alias: "battery_warning_motion_outside_nnw"
  id: "Batterivarning rörelse ute NNW"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_outside_nnw_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor ute NNW har {{ states('sensor.motion_outside_nnw_battery_level') }}% kvar"
#
- alias: "battery_warning_motion_outside_ssw"
  id: "Batterivarning rörelse ute SSW"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_outside_ssw_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor ute SSW har {{ states('sensor.motion_outside_ssw_battery_level') }}% kvar"
#
- alias: "battery_warning_motion_tvattstuga"
  id: "Batterivarning rörelse tvättstugan"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_tvattstuga_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor i tvättstugan har {{ states('sensor.motion_tvattstuga_battery') }}% kvar"
#
- alias: "battery_warning_motion_livingroom"
  id: "Batterivarning rörelse Vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_vardagsrum_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Rörelsesensor i vardagsrumstaket har {{ states('sensor.motion_vardagsrum_battery') }}% kvar"
#
- alias: "battery_warning_livingroom_smoke"
  id: "Batterivarning vardagsrum rökvarnare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.smoke_alarm_living_room_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Brandvarnare vardagsrum {{ states('sensor.smoke_alarm_living_room_battery') }}% kvar"
#
- alias: "battery_warning_basement_hallway_smoke"
  id: "Batterivarning källare hall rökvarnare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.smoke_basement_hallway_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Brandvarnare källare hall har {{ states('sensor.smoke_basement_hallway_battery') }}% kvar"
#
- alias: "battery_warning_bedroom_smoke"
  id: "Batterivarning sovrum rökvarnare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.smoke_bedroom_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Brandvarnare sovrum har {{ states('sensor.smoke_bedroom_battery') }}% kvar"
#
- alias: "battery_warning_dining_room_smoke"
  id: "Batterivarning matsal rökvarnare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.smoke_dining_room_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Brandvarnare matsal har {{ states('sensor.smoke_dining_room_battery') }}% kvar"
#
- alias: "battery_warning_hobbyrum_smoke"
  id: "Batterivarning hobbyrum rökvarnare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.smoke_office_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Brandvarnare hobbyrum har {{ states('sensor.smoke_office_battery') }}% kvar"
#
- alias: "battery_warning_hobbyrum_dimmer_switch"
  id: "Batterivarning hobbyrum dimmerswitch"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.switch_hobbyrum_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Hobbyrum dimmerfjärr har {{ states('sensor.switch_hobbyrum_battery') }}% kvar"
#
- alias: "battery_warning_bedroom_trv"
  id: "Batterivarning sovrum termostat"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.termostat_sovrum_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Sovrum termostat har {{ states('sensor.termostat_sovrum_battery') }}% kvar"
#
- alias: "battery_warning_basement_cat_vibration"
  id: "Batterivarning källare kattlucka vibration"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.vibration_kattlucka_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Källaren kattlucka vibratorsensor har {{ states('sensor.vibration_kattlucka_battery') }}% kvar"
#
- alias: "battery_warning_water_dishwasher"
  id: "Batterivarning Vattenvarning under diskhon"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.water_dish_battery_level
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Vattensensor under diskho {{ states('sensor.water_dish_battery_level') }}% kvar"
#
#
- alias: "battery_warning_airthings"
  id: "Batterivarning Airthings källare"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "18:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.basement_battery
      below: 10
  action:
    - service: notify.hanna_jimmy
      data: 
        title: "Batteri slut"
        message: "Airthings i källaren har {{ states('sensor.basement_battery') }}% kvar"
#
#
