#

#

- id: "lametric_dishes_time_left"
  alias: "LaMetric_-_dishes time left"
  initial_state: true
  mode: single
  trigger:
    - platform: time_pattern
      minutes: 6
    - platform: time_pattern
      minutes: 16
    - platform: time_pattern
      minutes: 26
    - platform: time_pattern
      minutes: 36
    - platform: time_pattern
      minutes: 46
    - platform: time_pattern
      minutes: 56
  condition:
    - condition: state
      entity_id: sensor.diskmaskin_operation_state
      state: "Run"
    - condition: numeric_state
      entity_id: sensor.diskmaskin_program_progress
      below: "100"
    - or:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
  action:
    - service: rest_command.lmvardagsrum_post_notification
      data:
        priority: info
        cycles: 2
        icon: a17590
        text: >
          {{ states('sensor.diskmaskin_program_progress') }}% klart, 
          {{ ((as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) - as_timestamp(now())) /60) | int }} 
          minuter kvar, klar {{ as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) | timestamp_custom('%H:%M') }}
    - service: rest_command.lmmatsal_post_notification
      data:
        priority: info
        cycles: 2
        icon: a17590
        text: >
          {{ states('sensor.diskmaskin_program_progress') }}% klart, 
          {{ ((as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) - as_timestamp(now())) /60) | int }} 
          minuter kvar, klar {{ as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) | timestamp_custom('%H:%M') }}
    - service: rest_command.lmsovrum_post_notification
      data:
        priority: info
        cycles: 2
        icon: a17590
        text: >
          {{ states('sensor.diskmaskin_program_progress') }}% klart, 
          {{ ((as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) - as_timestamp(now())) /60) | int }} 
          minuter kvar, klar {{ as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) | timestamp_custom('%H:%M') }}
    - service: rest_command.lmhobbyrum_post_notification
      data:
        priority: info
        cycles: 2
        icon: a17590
        text: >
          {{ states('sensor.diskmaskin_program_progress') }}% klart, 
          {{ ((as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) - as_timestamp(now())) /60) | int }} 
          minuter kvar, klar {{ as_timestamp(states.sensor.diskmaskin_remaining_program_time.state) | timestamp_custom('%H:%M') }}
#
- alias: "notification_dishes_done"
  id: "Notifiering när diskmaskinen är klar"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: switch.diskmaskin_power
      from: "on"
      to: "off"
      for: "00:00:05"
  condition:
    - condition: numeric_state
      entity_id: sensor.diskmaskin_program_progress
      above: "99"
    - condition: state
      entity_id: sensor.clt_l29_charger_type
      state: "none"
    - condition: state
      entity_id: sensor.hanna_charger_type
      state: "none"
    - or:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a17590
        text: "Diskmaskinen är klar!"
        category: notifications
        sound: positive2
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a17590
        text: "Diskmaskinen är klar!"
        category: notifications
        sound: positive2
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a17590
        text: "Diskmaskinen är klar!"
        category: notifications
        sound: positive2
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a17590
        text: "Diskmaskinen är klar!"
        category: notifications
        sound: positive2
        sound_repeat: 1
    - service: notify.hanna_jimmy
      data:
        title: "Diskmaskin klar"
        message: "Öppna luckan så det torkar"
        data:
          notification_icon: "mdi:dishwasher"
#
- alias: "dishes_done_remove_tablet"
  id: "Diskmaskinen är klar, ta bort en tablett"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.diskmaskin_operation_state
      from: "Run"
  condition:
    - condition: numeric_state
      entity_id: sensor.diskmaskin_program_progress
      above: "98"
  action:
    - service: input_number.decrement
      entity_id: input_number.disktabletter
#
- alias: "dishwasher_tablets_almost_out"
  id: "Disktabletter snart slut"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: input_number.disktabletter
      below: 20
  action:
    - service: shopping_list.add_item
      data:
        name: "Disktabletter"
#
