############################################
##
## Theme automations
##
############################################

############################################
##
## All
##
############################################

- alias: "windows_on"
  id: "Fönster På"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1.1
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.vardagsfonster
          - light.vardagsrum_fonster_balkong
          - light.matsal_bursprak_v
          - light.matsal_fonster_inglasning
          - light.matsal_bursprak_h
          - light.kontorsfonster
      data:
        brightness: 25
        color_temp: 153
    - delay:
        seconds: 1
    - service: light.turn_on
      target:
        entity_id:
          - light.parkering_trapp_1
          - light.parkering_trapp_2
          - light.garage_ute
      data:
        brightness: 2
        color_temp: 153
    - delay:
        seconds: 1
    - service: light.turn_on
      target:
        entity_id:
          - light.outside_impress_west_left
          - light.outside_impress_west_right
      data:
        brightness: 60
        color_temp: 320
#
- alias: "windows_off"
  id: "Fönster Av"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 1.1
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 1
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.vardagsfonster
          - light.matsal_bursprak_v
          - light.matsal_fonster_inglasning
          - light.matsal_bursprak_h
          - light.vardagsrum_fonster_balkong
          - light.kontorsfonster
          - light.parkering_trapp_1
          - light.parkering_trapp_2
          - light.garage_ute
          - light.outside_impress_west_left
          - light.outside_impress_west_right
    - delay:
        seconds: 1
    - service: switch.turn_off
      target:
        entity_id: switch.vardagsrum_spis
#
- alias: "bad weather on"
  id: "Dåligt väder på"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Ingen nederbörd"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Ingen nederbörd"
  condition:
    - or:
      - and:
        - not:
          - condition: state
            entity_id: sensor.trafikverket_karlsvik_precipitation_type
            state: "unavailable"
        - not:
          - condition: state
            entity_id: sensor.trafikverket_karlsvik_precipitation_type
            state: "Ingen nederbörd"
      - and:
        - not:
          - condition: state
            entity_id: sensor.gagnbro_precipitation_type
            state: "unavailable"
        - not:
          - condition: state
            entity_id: sensor.gagnbro_precipitation_type
            state: "Ingen nederbörd"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.bad_weather
#
- alias: "bad weather off"
  id: "Dåligt väder av"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Ingen nederbörd"
      for:
        hours: 4
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Ingen nederbörd"
      for:
        hours: 4
  condition:
    - and:
      - or:
        - condition: state
          entity_id: sensor.trafikverket_karlsvik_precipitation_type
          state: "Ingen nederbörd"
          for: "03:59:50"
#        - "{{ as_timestamp(now()) - as_timestamp(states.sensor.trafikverket_karlsvik_precipitation_type.last_updated) > 14400 }}"
      - or:
        - condition: state
          entity_id: sensor.gagnbro_precipitation_type
          state: "Ingen nederbörd"
          for: "03:59:50"
#        - "{{ as_timestamp(now()) - as_timestamp(states.sensor.gagnbro_precipitation_type.last_updated) > 14400 }}"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.bad_weather
#
- alias: "last time rained"
  id: "Senast det kom nederbörd"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Snö"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Snö"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Snö"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Snö"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Regn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Regn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Regn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Regn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Duggregn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Duggregn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Duggregn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Duggregn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Hagel"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Hagel"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Hagel"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Hagel"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Snöblandat regn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Snöblandat regn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Snöblandat regn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Snöblandat regn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      from: "Underkylt regn"
    - platform: state
      entity_id: sensor.gagnbro_precipitation_type
      to: "Underkylt regn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      from: "Underkylt regn"
    - platform: state
      entity_id: sensor.trafikverket_karlsvik_precipitation_type
      to: "Underkylt regn"
  action:
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.last_time_rained
      data:
        timestamp: "{{ now().timestamp() }}"
#
