############################################
##
## Fan automations
##
############################################

############################################
##
## All
##
############################################

- alias: "bedroom_fan_condtion_temp_on"
  id: "Sovrumsfläkt beroende på temp På"
  initial_state: true
  mode: single
  trigger:
    - platform: time_pattern
      minutes: 0
    - platform: time_pattern
      minutes: 15
    - platform: time_pattern
      minutes: 30
    - platform: time_pattern
      minutes: 45
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "ac"
            - condition: numeric_state
              entity_id: sensor.sovrum
              above: "22.1"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.sovrum
                  state: "unavailable"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "ac"
            - condition: numeric_state
              entity_id: sensor.sovrum
              above: "22.1"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.sovrum
                  state: "unavailable"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.flakt_sovrum
#
- alias: "bedroom_fan_condtion_temp off"
  id: "Sovrumsfläkt beroende på temp Av"
  initial_state: true
  mode: single
  trigger:
    - platform: time_pattern
      minutes: 0
    - platform: time_pattern
      minutes: 15
    - platform: time_pattern
      minutes: 30
    - platform: time_pattern
      minutes: 45
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_fan_override
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.sovrum
          state: "unavailable"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "ac"
            - condition: numeric_state
              entity_id: sensor.sovrum
              below: "22.1"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "ac"
            - condition: numeric_state
              entity_id: sensor.sovrum
              below: "22.1"
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "none"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.flakt_sovrum
#
- alias: "bedroom_fan_override_reset"
  id: "Sovrumsfläktoverride resett"
  initial_state: true
  mode: single
  trigger:
    - platform: time_pattern
      minutes: 0
    - platform: time_pattern
      minutes: 15
    - platform: time_pattern
      minutes: 30
    - platform: time_pattern
      minutes: 45
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_fan_override
      state: "on"
      for:
        hours: 2
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_fan_override
#
