#
#
#
#
- alias: "Smoke Sensor hall RÖK"
  id: "Rökdeckare hall RÖK"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.hall_smoke_sensor_smoke_alarm_smoke_detected
    from: "off"
    to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* RÖKLARM!!!! *******"
#
- alias: "Smoke Sensor hall ingen rök"
  id: "Rökdecakre hall ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.hall_smoke_sensor_smoke_alarm_smoke_detected
    from: "on"
    to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* Rök borta *******"
#
- alias: "Smoke Sensor hall VÄRME"
  id: "Rökdeckare hall VARMT"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.hall_smoke_heat_alarm_overheat_detected
    from: "off"
    to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* VÄRMELARM 55+ grader!!!! *******"
#
- alias: "Smoke Sensor hall ingen värme"
  id: "Rökdecakre hall ingen mer värme"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.hall_smoke_heat_alarm_overheat_detected
    from: "on"
    to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* Värme borta *******"
#
#
- alias: "Smoke Sensor hall källare RÖK"
  id: "Rökdeckare hall källare RÖK"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.kallare_hall_smoke_smoke_alarm_smoke_detected
    from: "off"
    to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall källare: "
        message: "******* RÖKLARM!!!! *******"
#
- alias: "Smoke Sensor hall källare ingen rök"
  id: "Rökdecakre hall källare ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.kallare_hall_smoke_smoke_alarm_smoke_detected
    from: "on"
    to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall källare: "
        message: "******* Rök borta *******"
#
- alias: "Smoke Sensor hall källare VÄRME"
  id: "Rökdeckare hall källare VARMT"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.kallare_hall_smoke_heat_alarm_overheat_detected
    from: "off"
    to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall källare: "
        message: "******* VÄRMELARM 55+ grader!!!! *******"
#
- alias: "Smoke Sensor hall källare ingen värme"
  id: "Rökdecakre hall källare ingen mer värme"
  initial_state: true
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.kallare_hall_smoke_heat_alarm_overheat_detected
    from: "on"
    to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall källare: "
        message: "******* Värme borta *******"
#
