#
#
#
#
- alias: "Smoke Sensor hall RÖK"
  id: "Rökdeckare hall RÖK"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_smoke_sensor_smoke_alarm_smoke_detected
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* RÖKLARM!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor hall ingen rök"
  id: "Rökdeckare hall ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_smoke_sensor_smoke_alarm_smoke_detected
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* Rök borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
- alias: "Smoke Sensor hall VÄRME"
  id: "Rökdeckare hall VARMT"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_smoke_heat_alarm_overheat_detected
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* VÄRMELARM 55+ grader!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor hall ingen värme"
  id: "Rökdeckare hall ingen mer värme"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_smoke_heat_alarm_overheat_detected
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall övervåning: "
        message: "******* Värme borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
#
- alias: "Smoke Sensor vardagsrum RÖK"
  id: "Rökdeckare vardagsrum RÖK"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_alarm_living_room_smoke
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare vardagsrum: "
        message: "******* RÖKLARM!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor vardagsrum ingen rök"
  id: "Rökdeckare vardagsrum ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_alarm_living_room_smoke
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare vardagsrum: "
        message: "******* Rök borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
#
- alias: "Smoke Sensor källare hall RÖK"
  id: "Rökdeckare källare hall RÖK"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_basement_hallway_smoke
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall källare: "
        message: "******* RÖKLARM!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor källare hall ingen rök"
  id: "Rökdeckare källare hall ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_basement_hallway_smoke
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hall källare: "
        message: "******* Rök borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
#
- alias: "Smoke Sensor sovrum RÖK"
  id: "Rökdeckare sovrum RÖK"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_bedroom_smoke
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare sovrum: "
        message: "******* RÖKLARM!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor sovrum ingen rök"
  id: "Rökdeckare sovrum ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_bedroom_smoke
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare sovrum: "
        message: "******* Rök borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
#
- alias: "Smoke Sensor hobbyrum RÖK"
  id: "Rökdeckare hobbyrum RÖK"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_office_smoke
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hobbyrum: "
        message: "******* RÖKLARM!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor hobbyrum ingen rök"
  id: "Rökdeckare hobbyrum ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_office_smoke
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare hobbyrum: "
        message: "******* Rök borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
#
- alias: "Smoke Sensor matsal RÖK"
  id: "Rökdeckare matsal RÖK"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_dining_room_smoke
      from: "off"
      to: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare matsal: "
        message: "******* RÖKLARM!!!! *******"
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
#
- alias: "Smoke Sensor matsal ingen rök"
  id: "Rökdeckare matsal ingen mer rök"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_dining_room_smoke
      from: "on"
      to: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Brandvarnare matsal: "
        message: "******* Rök borta *******"
#    - service: scene.turn_off
#      target:
#        entity_id: scene.firealarm
#
#

#
- alias: "Firealarm ON"
  id: "Brandlarm PÅ"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.smoke_dining_room_smoke
        - binary_sensor.smoke_office_smoke
        - binary_sensor.smoke_bedroom_smoke
        - binary_sensor.smoke_basement_hallway_smoke
        - binary_sensor.smoke_alarm_living_room_smoke
        - binary_sensor.hall_smoke_sensor_smoke_alarm_smoke_detected
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id:
          - input_boolean.firealarm
#
- alias: "Firealarm OFF"
  id: "Brandlarm AV"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.smoke_dining_room_smoke
        - binary_sensor.smoke_office_smoke
        - binary_sensor.smoke_bedroom_smoke
        - binary_sensor.smoke_basement_hallway_smoke
        - binary_sensor.smoke_alarm_living_room_smoke
        - binary_sensor.hall_smoke_sensor_smoke_alarm_smoke_detected
      from: "on"
      to: "off"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id:
          - input_boolean.firealarm
#

#
- alias: "Firealarm signal ON"
  id: "Brandlarm signal PÅ"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.firealarm
      from: "off"
      to: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.smoke_alarm_living_room_alarm
          - switch.smoke_basement_hallway_alarm
          - switch.smoke_bedroom_alarm
          - switch.smoke_dining_room_alarm
          - switch.smoke_office_alarm
          - switch.hall_smoke_sensor
    - service: rest_command.lmhobbyrum_ssaver_off
    - service: rest_command.lmmatsal_ssaver_off
    - service: rest_command.lmvardagsrum_ssaver_off
    - service: rest_command.lmsovrum_ssaver_off
    - service: scene.turn_on
      target:
        entity_id: scene.firealarm
    - delay:
        seconds: 2
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a9832
        text: BRANDLARM!
        category: alarms
        sound: alarm3
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a9832
        text: BRANDLARM!
        category: alarms
        sound: alarm3
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a9832
        text: BRANDLARM!
        category: alarms
        sound: alarm3
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a9832
        text: BRANDLARM!
        category: alarms
        sound: alarm3
        sound_repeat: 1
#
- alias: "Firealarm signal OFF"
  id: "Brandlarm signal AV"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.firealarm
      from: "on"
      to: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.smoke_alarm_living_room_alarm
          - switch.smoke_basement_hallway_alarm
          - switch.smoke_bedroom_alarm
          - switch.smoke_dining_room_alarm
          - switch.smoke_office_alarm
          - switch.hall_smoke_sensor
#
