############################################
##
## Theme automations
##
############################################



############################################
##
## All
##
############################################


- alias: "going_to_sleep_hanna"
  id: "Släck allt när båda sover Hanna"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.h8324_is_charging
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.clt_l29_is_charging
    state: 'on'
  - condition: state
    entity_id: person.hanna
    state: 'home'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.sovrum
  - service: switch.turn_off
    data:
      entity_id: switch.sovrum
  - service: switch.turn_off
    data:
      entity_id: switch.vardags_tavla
  - service: switch.turn_off
    data:
      entity_id: switch.vardags_eld
  - service: switch.turn_off
    data:
      entity_id: switch.terrasstak
  - delay:
      seconds: 1
  - service: switch.turn_off
    data:
      entity_id: switch.vaxt_1
#  - service: switch.turn_off
#    data:
#      entity_id: switch.vaxt3
  - delay:
      seconds: 1
#  - service: shell_command.shutdown_speldator1
#  - service: shell_command.shutdown_speldator2
  - delay:
      seconds: 1
  - service: light.turn_off
    data:
      entity_id: light.osram_smart_e27_color_1
  - service: light.turn_off
    data:
      entity_id: light.trust_e27_color_1
  - service: light.turn_off
    data:
      entity_id: light.ensis_down
  - service: light.turn_off
    data:
      entity_id: light.ensis_up
  - service: remote.turn_off
    data:
      entity_id: remote.sovrum
  - service: switch.turn_off
    data:
      entity_id: switch.ljud_dator
  - service: remote.turn_off
    data:
      entity_id: remote.vardagsrum
  - delay:
      seconds: 1
#   - service: shell_command.lametric_dark
  - service: switch.turn_off
    data:
      entity_id: switch.sovrum2
  - service: switch.turn_off
    data:
      entity_id: switch.vardags_lavalampa
  - service: switch.turn_off
    data:
      entity_id: switch.office
  - service: light.turn_off
    data:
      entity_id: light.sovrum_jimmy
  - service: switch.turn_on
    data:
      entity_id: switch.kamera1
  - service: switch.turn_on
    data:
      entity_id: switch.kamera2
  - service: light.turn_off
    data:
      entity_id: light.hall_entre
  - delay:
      seconds: 1
  - service: light.turn_off
    data:
      entity_id: light.hall_stora
  - service: light.turn_off
    data:
      entity_id: light.hall_lilla
  - service: switch.turn_off
    data:
      entity_id: switch.flakt_vardags
  - service: light.turn_off
    data:
      entity_id: light.kokstak
  - service: light.turn_off
    data:
      entity_id: light.wled_verandan_soffa
  - service: light.turn_off
    data:
      entity_id: light.verandan_matbord
  - service: shell_command.lmsovrum_ssaver_on
  - service: light.turn_off
    data:
      entity_id: light.kallarhall
  - service: light.turn_off
    data:
      entity_id: light.kallartrapp
  - service: switch.turn_off
    data:
      entity_id: switch.toppar_matsal
  - service: switch.turn_off
    data:
      entity_id: switch.sub_mixer_matsal
#
- alias: "going_to_sleep_jimmy"
  id: "Släck allt när båda sover Jimmy"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.clt_l29_is_charging
    to: 'on'
  condition:
  - condition: state
    entity_id: person.jimmy
    state: 'home'
  - condition: state
    entity_id: binary_sensor.h8324_is_charging
    state: 'on'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.sovrum
  - service: switch.turn_off
    data:
      entity_id: switch.sovrum
  - service: switch.turn_off
    data:
      entity_id: switch.vardags_tavla
  - service: switch.turn_off
    data:
      entity_id: switch.vardags_eld
  - service: switch.turn_off
    data:
      entity_id: switch.terrasstak
  - delay:
      seconds: 1
  - service: switch.turn_off
    data:
      entity_id: switch.vaxt_1
#  - service: switch.turn_off
#    data:
#      entity_id: switch.vaxt3
  - delay:
      seconds: 1
#  - service: shell_command.shutdown_speldator1
#  - service: shell_command.shutdown_speldator2
  - delay:
      seconds: 1
  - service: light.turn_off
    data:
      entity_id: light.osram_smart_e27_color_1
  - service: light.turn_off
    data:
      entity_id: light.trust_e27_color_1
  - service: light.turn_off
    data:
      entity_id: light.ensis_down
  - service: light.turn_off
    data:
      entity_id: light.ensis_up
  - service: remote.turn_off
    data:
      entity_id: remote.sovrum
  - service: switch.turn_off
    data:
      entity_id: switch.ljud_dator
  - service: remote.turn_off
    data:
      entity_id: remote.vardagsrum
  - delay:
      seconds: 1
#  - service: shell_command.lametric_dark
  - service: switch.turn_off
    data:
      entity_id: switch.sovrum2
  - service: switch.turn_off
    data:
      entity_id: switch.vardags_lavalampa
  - service: switch.turn_off
    data:
      entity_id: switch.office
  - service: light.turn_off
    data:
      entity_id: light.sovrum_jimmy
  - delay:
      seconds: 1
  - service: switch.turn_on
    data:
      entity_id: switch.kamera1
  - service: switch.turn_on
    data:
      entity_id: switch.kamera2
  - service: light.turn_off
    data:
      entity_id: light.hall_entre
  - service: light.turn_off
    data:
      entity_id: light.hall_stora
  - service: light.turn_off
    data:
      entity_id: light.hall_lilla
  - delay:
      seconds: 1
  - service: switch.turn_off
    data:
      entity_id: switch.flakt_vardags
  - service: light.turn_off
    data:
      entity_id: light.kokstak
  - service: light.turn_off
    data:
      entity_id: light.wled_verandan_soffa
  - service: light.turn_off
    data:
      entity_id: light.verandan_matbord
  - service: shell_command.lmsovrum_ssaver_on
  - service: light.turn_off
    data:
      entity_id: light.kallarhall
  - service: light.turn_off
    data:
      entity_id: light.kallartrapp
  - service: switch.turn_off
    data:
      entity_id: switch.toppar_matsal
  - service: switch.turn_off
    data:
      entity_id: switch.sub_mixer_matsal
#
- alias: "sleep_hanna"
  id: "Hanna Sover"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.h8324_is_charging
    to: 'on'
  condition:
  - condition: state
    entity_id: person.hanna
    state: 'home'
  action:
  - service: cover.set_cover_position
    data:
      entity_id: cover.blind_bedroom
      position: 0
  - delay:
      minutes: 2
  - service: shell_command.lmsovrum_ssaver_on
#
- alias: "sleep_jimmy"
  id: "Jimmy Sover"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.clt_l29_is_charging
    to: 'on'
  condition:
  - condition: state
    entity_id: person.jimmy
    state: 'home'
  action:
  - service: cover.set_cover_position
    data:
      entity_id: cover.blind_bedroom
      position: 0
#
