############################################
##
## Theme automations
##
############################################

############################################
##
## All
##
############################################

- alias: "going_to_sleep_hanna"
  id: "Släck allt när båda sover Hanna"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.hanna_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
    - condition: or
      conditions:
        - not:
          - condition: state
            entity_id: person.jimmy
            state: "home"
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "ac"
            - condition: state
              entity_id: person.jimmy
              state: "home"
  action:
    - service: script.turn_on
      target:
        entity_id: script.sleep_or_not_home
    - delay:
        seconds: 1
    - service: shell_command.shutdown_speldator1
    - delay:
        seconds: 1
    - service: shell_command.shutdown_speldator2
    - delay:
        seconds: 1
    - service: rest_command.lmhobbyrum_ssaver_on
    - service: rest_command.lmmatsal_ssaver_on
    - service: rest_command.lmvardagsrum_ssaver_on
#
- alias: "going_to_sleep_jimmy"
  id: "Släck allt när båda sover Jimmy"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.clt_l29_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.jimmy
      state: "home"
    - condition: or
      conditions:
        - not:
          - condition: state
            entity_id: person.hanna
            state: "home"
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "ac"
            - condition: state
              entity_id: person.hanna
              state: "home"
  action:
    - service: script.turn_on
      target:
        entity_id: script.sleep_or_not_home
    - delay:
        seconds: 1
    - service: rest_command.lmsovrum_ssaver_on
    - service: rest_command.lmhobbyrum_ssaver_on
    - service: rest_command.lmmatsal_ssaver_on
    - service: rest_command.lmvardagsrum_ssaver_on
    - delay:
        seconds: 1
    - service: media_player.turn_off
      target:
        entity_id: media_player.sovrum
    - delay:
        seconds: 1
    - service: shell_command.shutdown_speldator1
    - delay:
        seconds: 1
    - service: shell_command.shutdown_speldator2
    - delay:
        seconds: 1
#
- alias: "sleep_hanna_above_25"
  id: "Hanna Sover över 25"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.hanna_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
    - condition: numeric_state
      entity_id: sensor.sovrum
      above: 25
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.blind_bedroom
        position: 16
    - delay:
        minutes: 2
    - service: rest_command.lmsovrum_ssaver_on
#
- alias: "sleep_jimmy_above_25"
  id: "Jimmy Sover över 25"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.clt_l29_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.jimmy
      state: "home"
    - condition: numeric_state
      entity_id: sensor.sovrum
      above: 25
  action:
    - service: cover.set_cover_position
      target:
        entity_id: cover.blind_bedroom
      data:
        position: 16
#
- alias: "sleep_hanna_below_25"
  id: "Hanna Sover under 25"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.hanna_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
    - condition: numeric_state
      entity_id: sensor.sovrum
      below: 25
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.blind_bedroom
        position: 2
    - delay:
        minutes: 2
    - service: rest_command.lmsovrum_ssaver_on
#
- alias: "sleep_jimmy_below_25"
  id: "Jimmy Sover under 25"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.clt_l29_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.jimmy
      state: "home"
    - condition: numeric_state
      entity_id: sensor.sovrum
      below: 25
  action:
    - service: cover.set_cover_position
      target:
        entity_id: cover.blind_bedroom
      data:
        position: 2
#
