############################################
##
## Theme automations
##
############################################



############################################
##
## All
##
############################################


- alias: "charge_station_off_manual"
  id: "Laddhörnan av efter manuell start"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: switch.garage_laddstationen
    to: "on"
    for:
      hours: 2
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.garage_laddstationen
#
- alias: "charge_station_off_weekly"
  id: "Laddhörnan av veckostart"
  initial_state: true
  mode: single
  trigger:
  - platform: time
    at: "10:00:00"
  condition:
  - condition: time
    weekday:
    - sat
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.garage_laddstationen
#
- alias: "charge_station_on_weekly"
  id: "Laddhörnan på veckostart"
  initial_state: true
  mode: single
  trigger:
  - platform: time
    at: "09:00:00"
  condition:
  - condition: time
    weekday:
    - sat
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.garage_laddstationen
#
- alias: "Svullo update notify Android"
  id: "Notifiering att Svullo har uppdatering"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "20:40:00"
  condition:
    - condition: state
      entity_id: binary_sensor.svullo_update_available
      state: "on"
  action:
    - service: notify.mobile_app_clt_l29
      data: 
        message: "Svullo har tillgänglig uppdatering"
#
- alias: "Pfsense update notify Android"
  id: "Notifiering att pfsense har uppdatering"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "20:40:00"
  condition:
    - condition: state
      entity_id: binary_sensor.pfsense_firmware_updates_available
      state: "on"
  action:
    - service: notify.mobile_app_clt_l29
      data: 
        message: "Pfsense har tillgänglig uppdatering"
#
