############################################
##
## Theme automations
##
############################################



############################################
##
## All
##
############################################


- id: 'Startup auto'
  alias: 'Startup Set'
  initial_state: true
  mode: single
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: homeassistant.update_entity
    entity_id: cover.blind_bedroom
#  - service: deconz.configure
#    entity_id: binary_sensor.motion_bedroom_jimmy
#    data:
#      config:
#        duration: 60
#  - service: deconz.configure
#    entity_id: binary_sensor.motion_bedroom_hanna
#    data:
#      config:
#        duration: 60
#
#  - service: deconz.configure
#    entity_id: binary_sensor.motion_outside_garage_presence
#    field: /config
#    data:
#      sensitivity: 3
#
- alias: "Hass restart notify Android"
  id: "Notifiering att HASS har startat om Android"
  initial_state: true
  mode: single
  trigger:
  - platform: numeric_state
    entity_id: sensor.uptime
    value_template: "{{ states('sensor.uptime') | round(1) }}"
    below: 0.2
  action:
  - service: notify.mobile_app_clt_l29
    data: 
      message: "Home Assistant har av någon anledning startat om"
#
