############################################
##
## Theme automations
##
############################################



############################################
##
## All
##
############################################


- id: "Startup auto"
  alias: "Startup Set"
  initial_state: true
  mode: single
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: homeassistant.update_entity
    entity_id: cover.blind_bedroom
#
- alias: "Hass restart notify Android"
  id: "Notifiering att HASS har startat om Android"
  initial_state: true
  mode: single
  trigger:
    - platform: template
      value_template: "{% if (as_timestamp(now()) +120) == as_timestamp(states('sensor.uptime')) %}true{% endif %}"
  action:
    - service: notify.mobile_app_clt_l29
      data: 
        message: "Home Assistant har av någon anledning startat om"
#
