############################################
##
## Color lights automations
##
############################################

############################################
##
## All
##
############################################

- alias: "incoming_call_hanna"
  id: "Inkommande samtal ljusvarning hanna"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.hanna_phone_state
      to: "ringing"
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.osram_smart_e27_color_1
          - light.ensis_up
          - light.sovrum_hanna
          - light.kontor_color_mitten_fram
          - light.kontor_color_hoger_fram
          - light.kontor_color_hoger_sida
          - light.kontor_color_roof
          - light.kontor_color_vanster_fram
          - light.kontor_color_vanster_bak_ovre
          - light.kontor_color_vanster_bak_mitten
          - light.kontor_color_vanster_bak_nedre
      data:
        brightness: 254
        effect: blink
    - service: switch.turn_on
      target:
        entity_id: switch.vardags_eld
    - service: notify.lmhobbyrum
      data:
        message: "Hanna, mobilen ringer!"
        data:
          icon: "a35"
          icon_type: "none"
          sound: "cat"
          priority: "warning"
          cycles: 3
    - service: notify.lmmatsal
      data:
        message: "Hanna, mobilen ringer!"
        data:
          icon: "a35"
          icon_type: "none"
          sound: "cat"
          priority: "warning"
          cycles: 3
    - service: notify.lmsovrum
      data:
        message: "Hanna, mobilen ringer!"
        data:
          icon: "a35"
          icon_type: "none"
          sound: "cat"
          priority: "warning"
          cycles: 3
    - service: notify.lmvardagsrum
      data:
        message: "Hanna, mobilen ringer!"
        data:
          icon: "a35"
          icon_type: "none"
          sound: "cat"
          priority: "warning"
          cycles: 3
#
- alias: "no_incoming_call_hanna"
  id: "Inkommande samtal ljusvarning AV hanna"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.hanna_phone_state
      from: "ringing"
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.ensis_up
          - light.osram_smart_e27_color_1
          - light.sovrum_hanna
          - light.kontor_color_mitten_fram
          - light.kontor_color_hoger_fram
          - light.kontor_color_hoger_sida
          - light.kontor_color_roof
          - light.kontor_color_vanster_fram
          - light.kontor_color_vanster_bak_ovre
          - light.kontor_color_vanster_bak_mitten
          - light.kontor_color_vanster_bak_nedre
          - light.kontor_color_hoger_bak_ovre
          - light.kontor_color_hoger_bak_mitten
          - light.kontor_color_hoger_bak_nedre
    - service: switch.turn_off
      target:
        entity_id: switch.vardags_eld
#
