############################################
##
## Leaving home Automations
##
############################################

############################################
##
## Car heater
##
############################################

- alias: "Car_heater_hanna_on"
  id: "Hannas motorvärmare PÅ"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: input_datetime.hanna_motorvarmare
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
    - condition: numeric_state
      entity_id: sensor.ute
      below: 6
    - condition: state
      entity_id: binary_sensor.workday_hanna
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.motorvarmare_hanna
#
- alias: "Car_heater_hanna_off"
  id: "Hannas motorvärmare AV"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: switch.motorvarmare_hanna
      to: "on"
      for: "03:00:00"
    - platform: state
      entity_id: person.hanna
      from: "home"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.motorvarmare_hanna

############################################
##
## All leave home
##
############################################

- alias: "leaving_home"
  id: "Inte hemma"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: person.jimmy
      from: "home"
    - platform: state
      entity_id: person.hanna
      from: "home"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.sleep_or_not_home
#
