############################################
##
## Leaving home Automations
##
############################################

############################################
##
## Car heater
##
############################################

- alias: "Car_heater_hanna_on"
  id: "Hannas motorvärmare PÅ"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: input_datetime.hanna_wakeup
  #    platform: template
  #    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.hanna_wakeup', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
  - condition: state
    entity_id: person.hanna
    state: "home"
  - "{{ states('sensor.ute') < '6' }}"
  #    - condition: template
  #      value_template: '{{ states.sensor.ute.state < "6" }}'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.motorvarmare_hanna
#
- alias: "Car_heater_hanna_off"
  id: "Hannas motorvärmare AV"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: switch.motorvarmare_hanna
      to: "on"
      for: "02:00:00"
    - platform: state
      entity_id: person.hanna
      from: "home"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.motorvarmare_hanna

############################################
##
## All leave home
##
############################################

- alias: "leaving_home"
  id: "Inte hemma"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: person.jimmy
      from: "home"
    - platform: state
      entity_id: person.hanna
      from: "home"
  condition:
    - "{{ not is_state('person.jimmy', 'home') }}"
    #  - condition: template
    #    value_template: "{{ not is_state('person.jimmy', 'home') }}"
    - "{{ not is_state('person.hanna', 'home') }}"
  #  - condition: template
  #    value_template: "{{ not is_state('person.hanna', 'home') }}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.office
    - service: switch.turn_off
      data:
        entity_id: switch.vardags_tavla
    - service: switch.turn_off
      data:
        entity_id: switch.vardags_eld
    - delay:
        seconds: 1
    - service: switch.turn_off
      data:
        entity_id: switch.ljud_dator
    - service: switch.turn_off
      data:
        entity_id: switch.terrasstak
    - delay:
        seconds: 1
    - service: switch.turn_off
      data:
        entity_id: switch.vaxt_1
#    - service: switch.turn_off
#      data:
#        entity_id: switch.vaxt3
    - delay:
        seconds: 1
    - service: switch.turn_on
      data:
        entity_id: switch.kamera1
    - service: switch.turn_on
      data:
        entity_id: switch.kamera2
    - service: remote.turn_off
      data:
        entity_id: remote.sovrum
    - delay:
        seconds: 1
    - service: remote.turn_off
      data:
        entity_id: remote.vardagsrum
    - service: media_player.turn_off
      data:
        entity_id: media_player.sovrum
    #  - service: shell_command.lametric_dark
    - delay:
        seconds: 1
    - service: switch.turn_off
      data:
        entity_id: switch.sovrum2
    - service: light.turn_off
      data:
        entity_id: light.osram_smart_e27_color_1
    - service: light.turn_off
      data:
        entity_id: light.trust_e27_color_1
    - service: switch.turn_off
      data:
        entity_id: switch.flakt_sovrum
    - service: switch.turn_off
      data:
        entity_id: switch.vardags_lavalampa
    - service: light.turn_off
      data:
        entity_id: light.ensis_down
    - service: light.turn_off
      data:
        entity_id: light.ensis_up
    - service: light.turn_off
      data:
        entity_id: light.sovrum_jimmy
    - service: light.turn_off
      data:
        entity_id: light.sovrum_hanna
    - service: light.turn_off
      data:
        entity_id: light.kontor_color_1
    - service: light.turn_off
      data:
        entity_id: light.kontor_color_2
    - service: light.turn_off
      data:
        entity_id: light.kontor_color_3
    - service: light.turn_off
      data:
        entity_id: light.hall_entre
    - service: light.turn_off
      data:
        entity_id: light.hall_lilla
    - service: light.turn_off
      data:
        entity_id: light.hall_stora
    - service: switch.turn_off
      data:
        entity_id: switch.flakt_vardags
    - service: light.turn_off
      data:
        entity_id: light.kokstak
    - service: light.turn_off
      data:
        entity_id: light.wled_verandan_soffa
    - service: light.turn_off
      data:
        entity_id: light.verandan_matbord
    - service: light.turn_off
      data:
        entity_id: light.kallarhall
    - service: light.turn_off
      data:
        entity_id: light.kallartrapp
    - service: switch.turn_off
      data:
        entity_id: switch.toppar_matsal
    - service: switch.turn_off
      data:
        entity_id: switch.sub_mixer_matsal
#
