############################################
##
## Theme automations
##
############################################

############################################
##
## All
##
############################################

- alias: "play_lights_tvdatorn"
  id: "Tittar på tv vardagsrum lyset"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "playing"
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      to: "Netflix"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.vardagsrum_spis
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: 100
        transition: 30
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "play_lametric_tvdatorn"
  id: "Tittar på tv vardagsrum LaMetric"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "playing"
    - platform: time_pattern
      minutes: 0
    - platform: time_pattern
      minutes: 10
    - platform: time_pattern
      minutes: 20
    - platform: time_pattern
      minutes: 30
    - platform: time_pattern
      minutes: 40
    - platform: time_pattern
      minutes: 50
  condition:
    - condition: state
      entity_id: media_player.tvdatorn
      state: "playing"
  action:
    - service: notify.lametric
      data:
        target: "LMVardagsrum"
        message: >-
          {% if is_state_attr('media_player.tvdatorn', 'media_content_type', 'tvshow') %}
            S{{ state_attr('media_player.tvdatorn', 'media_season') }}-{{ state_attr('media_player.tvdatorn', 'media_series_title') }} - E{{ state_attr('media_player.tvdatorn', 'media_episode') }}-{{ state_attr('media_player.tvdatorn', 'media_title') }}
          {% else %}
            {{ state_attr('media_player.tvdatorn', 'media_title') }}
          {% endif %}
        data:
          icon: "i10125"
          icon_type: "none"
          priority: "warning"
          cycles: 2
#
- alias: "inactive_lights_tvdatorn"
  id: "Tittar inte längre på tv vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "idle"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1.5
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.vardagsrum_spis
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "paused_tvdatorn"
  id: "Tv pausad vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "paused"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1.5
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.vardagsrum_spis
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "play_cover_tvdatorn"
  id: "Tittar på tv cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "playing"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -5
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.gardin_1
        position: 11
#
- alias: "inactive_off_cover_tvdatorn_tv"
  id: "Tittar inte längre på tv cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "inactive"
      for: "00:00:03"
    - platform: state
      entity_id: media_player.tvdatorn
      to: "idle"
      for: "00:00:03"
    - platform: state
      entity_id: media_player.tvdatorn
      to: "off"
    - platform: state
      entity_id: media_player.living_room_tv
      to: "off"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.gardin_1
#
- alias: "netflix_cover_livingroom_tv"
  id: "Tittar på netflix cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      to: "Netflix"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -5
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.gardin_1
        position: 11
#
- alias: "not_netflix_cover_livingroom_tv"
  id: "Tittar inte längre på netflix cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      from: Netflix
#    - platform: template
#      value_template: "{{ not is_state_attr('media_player.living_room_tv', 'source', 'Netflix') }}"
#  condition:
#    - or:
#      - condition: state
#        entity_id: media_player.living_room_tv
#        state: "HDMI1"
#      - condition: state
#        entity_id: media_player.living_room_tv
#        state: "HDMI2"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.gardin_1
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
