############################################
##
## Theme automations
##
############################################

############################################
##
## All
##
############################################

- alias: "play_lights_tvdatorn"
  id: "Tittar på tv vardagsrum lyset"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "playing"
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      to: "Netflix"
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      to: "SVT Play"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.vardagsrum_spis
    - service: light.turn_off
      target:
        entity_id: light.vardagsrum_tak_aurelle
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            130
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            160
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            190
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            220
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            254
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        transition: 30
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#    - service: light.turn_on
#      target:
#        entity_id:
#          - light.vardagsrum_tak_aurelle
#      data:
#        transition: 30
#        brightness: >-
#          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
#            50
#          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
#            80
#          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
#            110
#          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
#            140
#          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
#            170
#          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
#            0
#          {% else %}
#            0
#          {% endif %}
#        color_temp: 210
#
- alias: "play_lametric_tvdatorn"
  id: "Tittar på tv vardagsrum LaMetric"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "playing"
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: media_player.tvdatorn
      state: "playing"
  action:
    - service: rest_command.lmvardagsrum_post_notification
      data:
        priority: warning
        cycles: 2
        text: >-
          {% if is_state_attr('media_player.tvdatorn', 'media_content_type', 'tvshow') %}
            S{{ state_attr('media_player.tvdatorn', 'media_season') }}-{{ state_attr('media_player.tvdatorn', 'media_series_title') }} - E{{ state_attr('media_player.tvdatorn', 'media_episode') }}-{{ state_attr('media_player.tvdatorn', 'media_title') }}
          {% else %}
            {{ state_attr('media_player.tvdatorn', 'media_title') }}
          {% endif %}
        icon: "i10125"
#
- alias: "inactive_lights_tvdatorn"
  id: "Tittar inte längre på tv vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "idle"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1.5
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.vardagsrum_spis
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        transition: 30
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      target:
        entity_id:
          - light.vardagsrum_tak_aurelle
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            2
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            35
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            70
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            100
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            130
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        color_temp: 210
#
- alias: "paused_tvdatorn"
  id: "Tv pausad vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "paused"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1.5
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.vardagsrum_spis
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        transition: 30
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      target:
        entity_id:
          - light.vardagsrum_tak_aurelle
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            2
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            35
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            70
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            100
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            130
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        color_temp: 210
#
- alias: "play_cover_tvdatorn"
  id: "Tittar på tv cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "playing"
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: media_player.tvdatorn
      state: "playing"
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -5
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.gardin_1
        position: 11
#
- alias: "inactive_off_cover_tvdatorn_tv"
  id: "Tittar inte längre på tv cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tvdatorn
      to: "inactive"
      for: "00:00:03"
    - platform: state
      entity_id: media_player.tvdatorn
      to: "idle"
      for: "00:00:03"
    - platform: state
      entity_id: media_player.tvdatorn
      to: "off"
    - platform: state
      entity_id: media_player.living_room_tv
      to: "off"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.gardin_1
#
- alias: "netflix_cover_livingroom_tv"
  id: "Tittar på netflix cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      to: "Netflix"
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      to: "SVT Play"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -5
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.gardin_1
        position: 11
#
- alias: "not_netflix_cover_livingroom_tv"
  id: "Tittar inte längre på netflix cover vardagsrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      from: "Netflix"
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: source
      from: "SVT Play"
#    - platform: template
#      value_template: "{{ not is_state_attr('media_player.living_room_tv', 'source', 'Netflix') }}"
  condition:
    - not:
      - condition: state
        entity_id: media_player.living_room_tv
        state: "Netflix"
    - not:
      - condition: state
        entity_id: media_player.living_room_tv
        state: "SVT Play"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.gardin_1
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        transition: 30
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      target:
        entity_id:
          - light.vardagsrum_tak_aurelle
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            2
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            35
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            70
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            100
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            130
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        color_temp: 210
#
