############################################
##
## Motion triggered lights automations
##
############################################

############################################
##
## All
##
############################################

- alias: "matsal_on_motion"
  id: "Matsal På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_matsal
      to: "on"
  condition:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 3
      - condition: numeric_state
        entity_id: sensor.ljus_ute
        below: 400
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.matsal_finn
          - switch.matsal_spel_slinga
#
- alias: "matsal_off_motion"
  id: "Matsal Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_matsal
      to: "off"
      for: "00:20:00"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.matsal_finn
          - switch.matsal_spel_slinga
#
- alias: "matsal_on_motion_ensis"
  id: "Matsal På Rörelse Ensis"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_matsal
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.firealarm
      state: "off"
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 3
      - condition: numeric_state
        entity_id: sensor.ljus_ute
        below: 400
    - condition: state
      entity_id: input_boolean.ensis_man_override
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.ensis_up
      data:
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "matsal_off_motion_ensis_up"
  id: "Matsal Av Rörelse Ensis Upp"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_matsal
      to: "off"
      for: "00:20:00"
  condition:
    - condition: state
      entity_id: input_boolean.firealarm
      state: "off"
    - condition: state
      entity_id: input_boolean.ensis_man_override
      state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.ensis_up
      data:
        transition: 20
#
- alias: "matsal_off_motion_ensis_down"
  id: "Matsal Av Rörelse Ensis Ner"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_matsal
      to: "off"
      for: "00:20:00"
  condition:
    - condition: state
      entity_id: input_boolean.firealarm
      state: "off"
    - condition: state
      entity_id: input_boolean.ensis_man_override
      state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.ensis_down
      data:
        transition: 20
#
- alias: "matsal_off_motion_sound"
  id: "Matsal Av Rörelse Ljud"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_matsal
      to: "off"
      for: "03:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.toppar_matsal
          - switch.sub_matsal
          - switch.mixer_matsal
#
- alias: "Ensis_Reset_manual_override"
  id: "Ensis override reset"
  initial_state: true
  mode: single
  trigger:
    platform: time
    at: "04:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.ensis_man_override
#
