##
#
#
#
##

- alias: "office_pc_on_motion_on_lights"
  id: "Kontor Dator på Rörelse PÅ ljus"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "on"
  condition:
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.speldator1
          state: "on"
        - condition: state
          entity_id: switch.speldator2
          state: "on"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.office_pc_on_motion_on_lights', 'last_triggered')) |int(0) ) > 1 }}"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 3
        - condition: numeric_state
          entity_id: sensor.ljus_ute
          below: 750
  action:
    - service: light.turn_on
      target:
        entity_id: light.kontor_color_mitten_fram
      data:
        effect: finish_effect
        brightness: 254
        color_name: >
          {% if states('sensor.clt_l29_battery_level') | float >= 80 %}
            darkgreen
          {% elif states('sensor.clt_l29_battery_level') | float < 80 and states('sensor.clt_l29_battery_level') | float >= 60 %}
            green
          {% elif states('sensor.clt_l29_battery_level') | float < 60 and states('sensor.clt_l29_battery_level') | float >= 40 %}
            yellow
          {% elif states('sensor.clt_l29_battery_level') | float < 40 and states('sensor.clt_l29_battery_level') | float >= 30 %}
            darkorange
          {% elif states('sensor.clt_l29_battery_level') | float < 30 %}
            darkred
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      target:
        entity_id:
          - light.kontor_color_hoger_fram
          - light.kontor_color_hoger_sida
          - light.kontor_color_roof
          - light.kontor_color_vanster_fram
          - light.kontor_color_vanster_bak_ovre
          - light.kontor_color_vanster_bak_mitten
          - light.kontor_color_vanster_bak_nedre
          - light.kontor_color_hoger_bak_ovre
          - light.kontor_color_hoger_bak_mitten
          - light.kontor_color_hoger_bak_nedre
      data:
        effect: finish_effect
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "office_pc_on_motion_on_switch"
  id: "Kontor Dator på Rörelse PÅ brytaren"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "on"
  condition:
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.speldator1
          state: "on"
        - condition: state
          entity_id: switch.speldator2
          state: "on"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.office_pc_on_motion_on_switch', 'last_triggered')) |int(0) ) > 1 }}"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.office
#
- alias: "office_pc_off_motion_on_lights"
  id: "Kontor Dator av Rörelse PÅ ljus"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "on"
  condition:
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - condition: state
      entity_id: switch.speldator1
      state: "off"
    - condition: state
      entity_id: switch.speldator2
      state: "off"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.office_pc_off_motion_on_lights', 'last_triggered')) |int(0) ) > 1 }}"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 3
        - condition: numeric_state
          entity_id: sensor.ljus_ute
          below: 750
  action:
    - service: light.turn_on
      target:
        entity_id: light.kontor_color_mitten_fram
      data:
        brightness: 254
        color_name: white
    - service: light.turn_on
      target:
        entity_id:
          - light.kontor_color_hoger_fram
          - light.kontor_color_hoger_sida
          - light.kontor_color_roof
          - light.kontor_color_vanster_fram
          - light.kontor_color_vanster_bak_ovre
          - light.kontor_color_vanster_bak_mitten
          - light.kontor_color_vanster_bak_nedre
          - light.kontor_color_hoger_bak_ovre
          - light.kontor_color_hoger_bak_mitten
          - light.kontor_color_hoger_bak_nedre
      data:
        brightness: 254
        color_name: white
#
- alias: "office_pc_off_motion_on_sound"
  id: "Kontor Dator av Rörelse PÅ ljud"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "on"
  condition:
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - condition: state
      entity_id: switch.speldator1
      state: "off"
    - condition: state
      entity_id: switch.speldator2
      state: "off"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.office_pc_off_motion_on_sound', 'last_triggered')) |int(0) ) > 1 }}"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.office
#
- alias: "office_game_pc_on_motion_light"
  id: "Kontor Speldator På Rörelse ljus"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.speldator1_override
      state: "off"
    - condition: state
      entity_id: switch.speldator1
      state: "on"
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.office_game_pc_on_motion_light', 'last_triggered')) |int(0) ) > 1 }}"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 3
        - condition: numeric_state
          entity_id: sensor.ljus_ute
          below: 750
  variables:
    colors:
      - yellow
      - blue
      - green
      - purple
      - red
      - pink
      - orange
      - cyan
      - indigo
      - darkblue
      - tomato
      - darkgreen
    speeds:
      - 8
      - 16
      - 32
      - 64
      - 128
  action:
    - service: light.turn_on
      target:
        entity_id: light.wled_speldator
      data:
        brightness: 60
        color_name: "{{ colors | random }}"
        effect: "{{ state_attr('light.wled_speldator', 'effect_list') | random }}"
    - service: number.set_value
      data:
        entity_id: number.wled_speldator_speed
        value: "{{ speeds | random }}"
#
- alias: "office_gamepc_override_wled"
  id: "hobbyrum speldator override wled"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.speldator1_override
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.wled_speldator
      data:
        brightness: 254
        color_name: white
        effect: "Solid"
#
- alias: "office_game_pc_on_motion_sound"
  id: "Kontor Speldator På Rörelse ljud"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.speldator1_override
      state: "off"
    - condition: state
      entity_id: switch.speldator1
      state: "on"
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.office_game_pc_on_motion_sound', 'last_triggered')) |int(0) ) > 1 }}"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.ljud_dator
#
- alias: "office_motion_off"
  id: "Kontor Dator Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office_group
      to: "off"
      for: "00:10:00"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.office
          - switch.ljud_dator
    - service: light.turn_off
      target:
        entity_id:
          - light.kontor_color_mitten_fram
          - light.kontor_color_hoger_fram
          - light.kontor_color_hoger_sida
          - light.kontor_color_roof
          - light.kontor_color_vanster_fram
          - light.kontor_color_vanster_bak_ovre
          - light.kontor_color_vanster_bak_mitten
          - light.kontor_color_vanster_bak_nedre
          - light.kontor_color_hoger_bak_ovre
          - light.kontor_color_hoger_bak_mitten
          - light.kontor_color_hoger_bak_nedre
          - light.wled_speldator
      data:
        transition: 20
    - service: media_player.turn_off
      target:
        entity_id: media_player.hobbyrum
#
