#
#
#
#


- alias: "kitchen_cabinet_on_motion"
  id: "Kök Vitrin På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kok
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.kok_vitrin
#
- alias: "kitchen_roof_on_motion"
  id: "Kökstak På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kok
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_roof_override
      state: "off"
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
            - condition: state
              entity_id: person.hanna
              state: "not_home"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.h8324_charger_type
              state: "none"
            - condition: state
              entity_id: person.jimmy
              state: "not_home"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.h8324_charger_type
              state: "none"
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 6
        - condition: numeric_state
          entity_id: sensor.ljus_ute
          below: 1000
  action:
    - service: light.turn_on
      target:
        entity_id: light.kokstak
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            2
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            35
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            70
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            100
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            130
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        color_temp: 153
#
- alias: "kitchen_off_motion"
  id: "Kök Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kok
      to: "off"
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_roof_override
      state: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.kok_vitrin
    - service: light.turn_off
      target:
        entity_id: light.kokstak
      data:
        transition: 20
#
- alias: "kitchen_roof_Reset_manual_override"
  id: "Kökstak override reset"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kitchen_roof_override
#
