#
#
#

- alias: "livingroom_on_motion"
  id: "Vardagsrum På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_vardagsrum
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.firealarm
      state: "off"
    - condition: state
      entity_id: input_boolean.dark_mode
      state: "off"
    - or:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 3
      - condition: numeric_state
        entity_id: sensor.ljus_ute
        below: 400
    - not:
      - condition: state
        entity_id: media_player.tvdatorn
        state: "playing"
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: person.jimmy
          state: "home"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: person.hanna
          state: "home"
  action:
    - service: switch.turn_on
      target:
        entity_id: 
          - switch.vardagsrum_spis
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      target:
        entity_id:
          - light.vardagsrum_tak_aurelle
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            50
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            80
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            110
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            140
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            170
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        color_temp: 210
#
- alias: "livingroom_off_motion"
  id: "Vardagsrum Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_vardagsrum
      to: "off"
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.firealarm
      state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.osram_smart_e27_color_1
          - light.vardagsrum_tak_aurelle
      data:
        transition: 20
    - service: switch.turn_off
      target:
        entity_id: 
          - switch.vardagsrum_spis
#
- alias: "livingroom_off_media"
  id: "Vardagsrum Av media"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: "on"
      for: "00:15:00"
  condition:
    - condition: state
      entity_id: input_boolean.firealarm
      state: "off"
    - condition: state
      entity_id: binary_sensor.motion_vardagsrum
      state: "off"
      for: "00:04:58"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.osram_smart_e27_color_1
          - light.vardagsrum_tak_aurelle
      data:
        transition: 20
    - service: switch.turn_off
      target:
        entity_id: 
          - switch.vardagsrum_spis
#
- alias: "dark_mode_manual_override_reset"
  id: "Dark mode override reset"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.dark_mode
      to: "on"
      for: "01:20:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.dark_mode
#
