#
#
#
#

- alias: "kitchen_cabinet_on_motion"
  id: "Kök Vitrin På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kok
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
            - not:
              - condition: state
                entity_id: person.hanna
                state: "home"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "none"
            - not:
              - condition: state
                entity_id: person.jimmy
                state: "home"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "none"
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
    - condition: state
      entity_id: binary_sensor.kok_spritskap_dorr_contact
      state: "off"
      for:
        seconds: 30
#    - condition: state
#      entity_id: binary_sensor.motion_kok
#      state: "off"
#      for:
#        minutes: 4
  variables:
    colors:
      - yellow
      - blue
      - green
      - purple
      - red
      - pink
      - orange
      - cyan
      - indigo
      - darkblue
      - tomato
      - darkgreen
  action:
    - service: light.turn_on
      target:
        entity_id: light.spritskap
      data:
        brightness: 150
        color_name: "{{ colors | random }}"
        effect: "Random Colors"
    - service: number.set_value
      data:
        entity_id: number.spritskap_speed
        value: "8"
#
- alias: "kitchen_cabinet_door_open"
  id: "Kök Vitrin dörr öppnas"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.kok_spritskap_dorr_contact
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.spritskap
      data:
        brightness: 254
        color_name: white
        effect: "Solid"
#
- alias: "kitchen_roof_on_motion"
  id: "Kökstak På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kok
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_roof_override
      state: "off"
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
            - not:
              - condition: state
                entity_id: person.hanna
                state: "home"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "none"
            - not:
              - condition: state
                entity_id: person.jimmy
                state: "home"
        - condition: and
          conditions:
            - condition: state
              entity_id: person.hanna
              state: "home"
            - condition: state
              entity_id: sensor.hanna_charger_type
              state: "none"
            - condition: state
              entity_id: person.jimmy
              state: "home"
            - condition: state
              entity_id: sensor.clt_l29_charger_type
              state: "none"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 6
        - condition: numeric_state
          entity_id: sensor.ljus_ute
          below: 1000
  action:
    - service: light.turn_on
      target:
        entity_id: light.kokstak
      data:
        brightness: >-
          {% if state_attr("sun.sun", "elevation") | float <= -5 %}
            2
          {% elif state_attr("sun.sun", "elevation") | float > -5 and state_attr("sun.sun", "elevation") | float <= -2 %}
            35
          {% elif state_attr("sun.sun", "elevation") | float > -2 and state_attr("sun.sun", "elevation") | float <= 1 %}
            70
          {% elif state_attr("sun.sun", "elevation") | float > 1 and state_attr("sun.sun", "elevation") | float <= 5 %}
            100
          {% elif state_attr("sun.sun", "elevation") | float > 5 and state_attr("sun.sun", "elevation") | float < 7 %}
            130
          {% elif state_attr("sun.sun", "elevation") | float >= 7 %}
            0
          {% else %}
            0
          {% endif %}
        color_temp: 153
#
- alias: "kitchen_off_motion"
  id: "Kök Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kok
      to: "off"
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_roof_override
      state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.spritskap
    - service: light.turn_off
      target:
        entity_id: light.kokstak
      data:
        transition: 20
#
- alias: "kitchen_roof_Reset_manual_override"
  id: "Kökstak override reset"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kitchen_roof_override
#
- alias: "kitchen_sink_on_motion_not_charging"
  id: "kök diskbänk På Rörelse ej sova"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kok_diskbank
      to: "on"
  condition:
    - or:
      - and:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
      - and:
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
      - condition: state
        entity_id: input_boolean.visitors
        state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.kok_diskbank
      data:
        brightness: 40
#
- alias: "kitchen_sink_on_motion_charging"
  id: "Kök diskbänk På Rörelse när laddas"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kok_diskbank
      to: "on"
  condition:
    - or:
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "ac"
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "ac"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "off"
      - and:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "ac"
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - not:
          - condition: state
            entity_id: person.hanna
            state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "off"
      - and:
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "ac"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - not:
          - condition: state
            entity_id: person.jimmy
            state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "off"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.kok_diskbank
      data:
        brightness: 2
#
- alias: "kitchen_sink_off_motion_not_charging"
  id: "Kök diskbänk Av Rörelse ej sova"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kok_diskbank
      to: "off"
      for: "00:02:00"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.kok_diskbank
      data:
        transition: 20
#
- alias: "kitchen_sink_off_motion_charging"
  id: "Kök diskbänk Av Rörelse Sover"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kok_diskbank
      to: "off"
  condition:
    - and:
      - condition: state
        entity_id: sensor.clt_l29_charger_type
        state: "ac"
      - condition: state
        entity_id: person.jimmy
        state: "home"
      - condition: state
        entity_id: input_boolean.visitors
        state: "off"
    - and:
      - condition: state
        entity_id: sensor.hanna_charger_type
        state: "ac"
      - condition: state
        entity_id: person.hanna
        state: "home"
      - condition: state
        entity_id: input_boolean.visitors
        state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.kok_diskbank
      data:
        transition: 20
#
