



#
- alias: "basement_washroom_roof_on"
  id: "källare tvättstuga tak På"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_tvattstuga_occupancy
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.tvattstuga_tak
      data:
        brightness: 254
        color_temp: 180
#
- alias: "basement_washroom_roof_off"
  id: "källare tvättstuga tak Av"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_tvattstuga_occupancy
      to: "off"
      for:
        minutes: 3
  action:
    - service: light.turn_off
      target:
        entity_id: light.tvattstuga_tak
      data:
        transition: 20
#
