



- alias: "bedroom_on_motion_jimmy_charging"
  id: "Sovrum På Rörelse Jimmy Laddar"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_jimmy
    to: 'on'
  condition:
  - condition: state
    entity_id: person.jimmy
    state: 'home'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.clt_l29_is_charging
      state: 'on'
    - condition: state
      entity_id: binary_sensor.h8324_is_charging
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.sovrum_jimmy
      brightness: 40
      color_name: red
#
- alias: "bedroom_on_motion_jimmy_not_charging"
  id: "Sovrum På Rörelse Jimmy Laddar EJ"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_jimmy
    to: 'on'
  condition:
  - condition: state
    entity_id: person.jimmy
    state: 'home'
  - condition: state
    entity_id: binary_sensor.clt_l29_is_charging
    state: 'off'
  - condition: state
    entity_id: binary_sensor.h8324_is_charging
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.sovrum_jimmy
      brightness: 254
      color_name: >
        {{ ['white', 'yellow', 'blue', 'green', 'purple', 'pink', 'orange', 'cyan'] |random }}
#
- alias: "bedroom_off_motion_jimmy_charging"
  id: "Sovrum Av Rörelse Jimmy Laddar"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_jimmy
    to: 'off'
    for: '00:00:01'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.clt_l29_is_charging
      state: 'on'
    - condition: state
      entity_id: binary_sensor.h8324_is_charging
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.sovrum_jimmy
#
- alias: "bedroom_off_motion_jimmy_not_charging"
  id: "Sovrum Av Rörelse Jimmy Laddar EJ"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_jimmy
    to: 'off'
    for: '00:15:00'
#  condition:
  action:
  - service: light.turn_off
    data:
      entity_id: light.sovrum_jimmy
#
- alias: "bedroom_on_motion_hanna_charging"
  id: "Sovrum På Rörelse Hanna Laddar"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_hanna
    to: 'on'
  condition:
  - "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
#  - condition: template
#    value_template: "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
  - condition: state
    entity_id: person.hanna
    state: 'home'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.clt_l29_is_charging
      state: 'on'
    - condition: state
      entity_id: binary_sensor.h8324_is_charging
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.sovrum_hanna
      brightness: 40
      color_name: red
#
- alias: "bedroom_on_motion_hanna_not_charging"
  id: "Sovrum På Rörelse Hanna Laddar EJ"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_hanna
    to: 'on'
  condition:
  - "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
#  - condition: template
#    value_template: "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
  - condition: state
    entity_id: person.hanna
    state: 'home'
  - condition: state
    entity_id: binary_sensor.clt_l29_is_charging
    state: 'off'
  - condition: state
    entity_id: binary_sensor.h8324_is_charging
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.sovrum_hanna
      brightness: 254
      color_name: >
        {{ ['white', 'yellow', 'blue', 'green', 'purple', 'pink', 'orange', 'cyan'] |random }}
#
- alias: "bedroom_off_motion_hanna_charging"
  id: "Sovrum Av Rörelse Hanna Laddar"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_hanna
    to: 'off'
    for: '00:00:01'
  condition:
  - "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
#  - condition: template
#    value_template: "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.clt_l29_is_charging
      state: 'on'
    - condition: state
      entity_id: binary_sensor.h8324_is_charging
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.sovrum_hanna
#
- alias: "bedroom_off_motion_hanna_not_charging"
  id: "Sovrum Av Rörelse Hanna Laddar EJ"
  initial_state: true
  mode: single
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_bedroom_hanna
    to: 'off'
    for: '00:15:00'
  condition:
  - "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
#  - condition: template
#    value_template: "{{ not is_state('input_boolean.hanna_svorum_man_override', 'on') }}"
  action:
  - service: light.turn_off
    data:
      entity_id: light.sovrum_hanna
#
- alias: "Hanna_sovrum_Reset_manual_override"
  id: "Hanna manuell override reset"
  initial_state: true
  mode: single
  trigger:
    platform: time
    at: "00:00:01"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.hanna_svorum_man_override
#
