#
- alias: "basement_stairs_on_motion"
  id: "Källartrapp På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kallartrapp
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_hallway_downstairs_presence
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.kallartrapp
      data:
        brightness: 180
        color_temp: 153
    - service: light.turn_on
      target:
        entity_id: light.kallarhall
      data:
        brightness: 200
        color_temp: 153
#
- alias: "basement_stairs_off_motion"
  id: "Källartrapp Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kallartrapp
      to: "off"
      for: "00:05:01"
    - platform: state
      entity_id: binary_sensor.motion_hallway_downstairs_presence
      to: "off"
      for: "00:05:01"
    - platform: state
      entity_id: binary_sensor.vibration_kattlucka_vibration
      to: "off"
      for: "00:01:00"
  condition:
    - condition: state
      entity_id:
        - binary_sensor.motion_kallartrapp
        - binary_sensor.motion_hallway_downstairs_presence
      state: "off"
      for:
        minutes: 5
  action:
    - service: light.turn_off
      target:
        entity_id: 
          - light.kallartrapp
          - light.kallarhall
      data:
        transition: 20
#
- alias: "basement_hallway_on_motion_office"
  id: "Källarhall På Rörelse hobbyrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_downstairs_presence
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
  action:
    - service: light.turn_on
      target:
        entity_id: light.kontor_color_roof
      data:
        brightness: 254
        color_temp: 153
#
- alias: "basement_hallway_off_motion_office"
  id: "Källarhall Av Rörelse hobbyrum"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kallartrapp
      to: "off"
      for: "00:05:01"
    - platform: state
      entity_id: binary_sensor.motion_hallway_downstairs_presence
      to: "off"
      for: "00:05:01"
  condition:
    - condition: state
      entity_id: binary_sensor.motion_office
      state: "off"
      for: "00:19:59"
    - condition: state
      entity_id: binary_sensor.motion_hobbyrum_speldator
      state: "off"
      for: "00:19:59"
  action:
    - service: light.turn_off
      target:
        entity_id: light.kontor_color_roof
      data:
        transition: 20
#
- alias: "basement_foodstorage_on"
  id: "Matkällare På"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.kallare_matkallare
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.kallare_matkallare
      data:
        brightness: 254
        color_temp: 153
#
- alias: "basement_foodstorage_off"
  id: "Matkällare Av"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.kallare_matkallare
      to: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.kallare_matkallare
      data:
        transition: 20
#
- alias: "boiler_room_downstairs_on_motion"
  id: "Pannrum källare På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kallare_pannrum_occupancy
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.kallare_pannrum_tak
      data:
        brightness: 253
        color_temp: 153
#
- alias: "boiler_room_downstairs_off_motion"
  id: "Pannrum källare Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kallare_pannrum_occupancy
      to: "off"
      for: "00:03:00"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.kallare_pannrum_tak
      data:
        transition: 20
#
- alias: "basement_cat_on_vibration"
  id: "Källare kattlucka På Vibration"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_kattlucka_vibration
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.visitors
      state: "off"
  action:
    - service: light.turn_on
      target:
        entity_id: light.kallarhall
      data:
        brightness: 30
        color_temp: 153
#
