#
#
#
#

- alias: "closet_on_motion"
  id: "Garderob På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_garderob
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.clt_l29_charger_type
          state: "none"
        - condition: state
          entity_id: sensor.hanna_charger_type
          state: "none"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.garderob
          - light.hall_stora
      data:
        brightness: 254
#
- alias: "closet_off_motion"
  id: "Garderob Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_garderob
      to: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.garderob
      data:
        transition: 20
    - delay:
        seconds: 10
    - service: light.turn_off
      target:
        entity_id: light.hall_stora
      data:
        transition: 20
#
