#
#
#

- alias: "livingroom_on_motion"
  id: "Vardagsrum På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_vardagsrum
      to: "on"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 3
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.tvdatorn
          state: "playing"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: 
          - switch.vardagsrum_spis
          - switch.vardags2
    - service: light.turn_on
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "livingroom_off_motion"
  id: "Vardagsrum Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_vardagsrum
      to: "off"
      for: "00:03:00"
  action:
    - service: light.turn_off
      target:
        entity_id: light.osram_smart_e27_color_1
      data:
        transition: 20
    - service: switch.turn_off
      target:
        entity_id: 
          - switch.vardagsrum_spis
          - switch.vardags2
#
