##
#
#
#
##

- alias: "office_pc_on_motion"
  id: "Kontor Dator På Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_hobbyrum_speldator
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.clt_l29_is_charging
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.office
    - service: switch.turn_on
      data:
        entity_id: switch.ljud_dator
    - service: light.turn_on
      data:
        entity_id: light.trust_e27_color_1
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      data:
        entity_id: light.kontor_color_1
        brightness: 254
        color_name: >
          {% if states('sensor.clt_l29_battery_level') | float >= 80 %}
            darkgreen
          {% elif states('sensor.clt_l29_battery_level') | float < 80 and states('sensor.clt_l29_battery_level') | float >= 60 %}
            green
          {% elif states('sensor.clt_l29_battery_level') | float < 60 and states('sensor.clt_l29_battery_level') | float >= 40 %}
            yellow
          {% elif states('sensor.clt_l29_battery_level') | float < 40 and states('sensor.clt_l29_battery_level') | float >= 30 %}
            darkorange
          {% elif states('sensor.clt_l29_battery_level') | float < 30 %}
            darkred
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      data:
        entity_id: light.kontor_color_2
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
    - service: light.turn_on
      data:
        entity_id: light.kontor_color_3
        brightness: 254
        color_name: >
          {% if states('sensor.ute') | float <= -8 %}
            indigo
          {% elif states('sensor.ute') | float > -8 and states('sensor.ute') | float <= 1 %}
            blue
          {% elif states('sensor.ute') | float > 1 and states('sensor.ute') | float <= 10 %}
            green
          {% elif states('sensor.ute') | float > 10 and states('sensor.ute') | float <= 18 %}
            yellow
          {% elif states('sensor.ute') | float > 18 and states('sensor.ute') | float < 25 %}
            darkorange
          {% elif states('sensor.ute') | float >= 25 %}
            red
          {% else %}
            white
          {% endif %}
#
- alias: "office_pc_off_motion"
  id: "Kontor Dator Av Rörelse"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office
      to: "off"
      for: "01:00:00"
    - platform: state
      entity_id: binary_sensor.motion_hobbyrum_speldator
      to: "off"
      for: "01:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.motion_office
      state: "off"
      for: "00:59:59"
    - condition: state
      entity_id: binary_sensor.motion_hobbyrum_speldator
      state: "off"
      for: "00:59:59"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.office
    - service: switch.turn_off
      data:
        entity_id: switch.ljud_dator
    - service: light.turn_off
      data:
        entity_id: light.trust_e27_color_1
    - service: light.turn_off
      data:
        entity_id: light.kontor_color_1
    - service: light.turn_off
      data:
        entity_id: light.kontor_color_2
    - service: light.turn_off
      data:
        entity_id: light.kontor_color_3
#
