#
#
#
#
#

- alias: "Sileno_error_undefined"
  id: "Sileno fel odefinierat"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: vacuum.sileno
      to: "error"
      for: "00:00:03"
  condition:
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
    - condition: not
      conditions:
        - condition: state
          entity_id: vacuum.sileno
          attribute: error
          state: "OFF_HATCH_OPEN"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Olle behöver hjälp!!"
        message: "Error: {{ state_attr('vacuum.sileno', 'error') }}"
#
- alias: "Sileno_should_charge"
  id: "Sileno borde ladda"
  initial_state: true
  mode: single
  trigger:
    platform: time
    at: "20:00:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: vacuum.sileno
          state: "docked"
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Olle behöver hjälp!!"
        message: "Jag borde ladda vid denna tiden, kom och hjälp mig."
#
