#
#
#
#


- alias: "sileno_Reset_manual_override"
  id: "Sileno reset manuell override"
  initial_state: true
  mode: single
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sileno_override
#
- alias: "Sileno_start"
  id: "Sileno starta"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: input_datetime.olle_start
    - platform: state
      entity_id: input_boolean.bad_weather
      to: "off"
    - platform: state
      entity_id: input_boolean.sileno_override
      to: "off"
    - platform: numeric_state
      entity_id: sensor.sileno_battery_level
      above: 99
    - platform: numeric_state
      entity_id: sensor.ute
      above: 8
    - platform: numeric_state
      entity_id: sensor.sun_elevation
      above: 15
    - platform: state
      entity_id: person.jimmy
      to: "home"
    - platform: state
      entity_id: person.hanna
      to: "home"
  condition:
    - condition: time
      after: input_datetime.olle_start
      before: input_datetime.olle_stop
    - condition: state
      entity_id: input_boolean.bad_weather
      state: "off"
    - condition: numeric_state
      entity_id: sensor.sileno_battery_level
      above: 99
    - condition: state
      entity_id: input_boolean.sileno_override
      state: "off"
    - condition: numeric_state
      entity_id: sensor.ute
      above: 8
    - condition: numeric_state
      entity_id: sensor.sun_elevation
      above: 15
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
  action:
    - service: vacuum.start
      target:
        entity_id: vacuum.sileno
#
- alias: "Sileno_parked_bad_weather"
  id: "Sileno parkerad dåligt väder"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.bad_weather
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
  action:
    - service: vacuum.stop
      target:
        entity_id: vacuum.sileno
#
- alias: "Sileno_parked_evening_schedule"
  id: "Sileno parkerad kvällsschema"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: input_datetime.olle_stop
  condition:
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
  action:
    - service: vacuum.stop
      target:
        entity_id: vacuum.sileno
#
- alias: "Sileno_parked_no_one_home"
  id: "Sileno parkerad ingen hemma"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: person.jimmy
      from: "home"
    - platform: state
      entity_id: person.hanna
      from: "home"
  condition:
    - not:
      - condition: state
        entity_id: person.hanna
        state: "home"
    - not:
      - condition: state
        entity_id: person.jimmy
        state: "home"
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
  action:
    - service: vacuum.stop
      target:
        entity_id: vacuum.sileno
#
- alias: "Sileno_stop"
  id: "Sileno stoppad"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: vacuum.sileno
      from: "docked"
    - platform: state
      entity_id: input_boolean.sileno_override
      to: "on"
    - platform: numeric_state
      entity_id: sensor.ute
      below: 8
    - platform: numeric_state
      entity_id: sensor.sun_elevation
      below: 15
  condition:
    - condition: state
      entity_id: input_boolean.sileno_winter_sleep
      state: "off"
    - or:
      - condition: time
        after: input_datetime.olle_stop
        before: input_datetime.olle_start
      - condition: state
        entity_id: input_boolean.bad_weather
        state: "on"
      - condition: state
        entity_id: input_boolean.sileno_override
        state: "on"
      - condition: numeric_state
        entity_id: sensor.ute
        below: 8
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        below: 15
      - and:
        - not:
          - condition: state
            entity_id: person.hanna
            state: "home"
        - not:
          - condition: state
            entity_id: person.jimmy
            state: "home"
  action:
    - service: vacuum.stop
      target:
        entity_id: vacuum.sileno
#
