#
#
#
- id: "tag_singalong_jimmy_matsal"
  alias: "Taggen Sing-along Jimmy är skannad till matsal"
  mode: single
  trigger:
    - platform: tag
      tag_id: 5962d3be-cabc-41ef-92f6-adced3467c1f
  action:
    - service: spotcast.start
      data:
        entity_id: media_player.audio_uppe
        uri: "spotify:playlist:3jaZ0FBYc89jfqx0m5aIyt?si=8581a2a9b37e45b6"
        random_song: true
#
- id: "tag_singalong_hanna_matsal"
  alias: "Taggen Sing-along Hanna är skannad till matsal"
  mode: single
  trigger:
    - platform: tag
      tag_id: 51468b48-ce07-4c45-8929-0f6f0409f02e
  action:
    - service: spotcast.start
      data:
        account: "fafnesbane"
        entity_id: media_player.audio_uppe
        uri: "spotify:playlist:3jaZ0FBYc89jfqx0m5aIyt?si=8581a2a9b37e45b6"
        random_song: true
        shuffle: true
#
- alias: "entre_manual_override_on"
  id: "Entre override på"
  initial_state: true
  mode: single
  trigger:
    - platform: tag
      tag_id: 40c50937-eae6-43db-aacb-a7b2143e196c
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "DOOR_OPEN_OUTSIDE"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.entrance_door_override
    - service: light.turn_on
      target:
        entity_id: light.hall_entre
      data:
        brightness: 2
        color_temp: 153
        effect: blink
#
- alias: "living_room_tv_on_tag"
  id: "Starta vardagsrumstvn via tag"
  initial_state: true
  mode: single
  trigger:
    - platform: tag
      tag_id:  6dcec5fa-5ec2-4d02-9022-a2c49c3c29b7
  action:
    - service: switch.toggle
      target:
        entity_id: switch.webostv_lg
#
