############################################
##
## Notifications Android app automations
##
############################################

############################################
##
## All
##
############################################

#
- alias: "door_to_outside_open"
  id: "Ytterdörren glömt stänga"
  initial_state: true
  mode: single
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition:
    - condition: state
      entity_id: binary_sensor.hall_door_magnet
      state: "on"
      for: "00:05:00"
    - condition: state
      entity_id: input_boolean.entrance_door_override
      state: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Någon har glömt stänga ytterdörren"
        data:
          notification_icon: "mdi:door-open"
          actions:
            - action: "DOOR_OPEN_OUTSIDE"
              title: "Aktivera override"
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 1
        icon: a15588
        text: "Ytterdörren är öppen"
        category: notifications
        sound: positive3
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 1
        icon: a15588
        text: "Ytterdörren är öppen"
        category: notifications
        sound: positive3
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 1
        icon: a15588
        text: "Ytterdörren är öppen"
        category: notifications
        sound: positive3
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 1
        icon: a15588
        text: "Ytterdörren är öppen"
        category: notifications
        sound: positive3
        sound_repeat: 1
#
- alias: "entrance_door_Reset_manual_override"
  id: "entredörr override reset"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_door_magnet
      to: "off"
      for: "01:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.entrance_door_override
#
- alias: "sleep_hanna_garagelas"
  id: "Hanna Sover garagelåset"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.hanna_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.hanna
      state: "home"
    - condition: state
      entity_id: binary_sensor.garagelas
      state: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Garagelåset"
        message: "Garaget är inte låst"
        data:
          notification_icon: "mdi:garage-lock"
#
- alias: "sleep_jimmy_garagelas"
  id: "Jimmy Sover Garagelåset"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.clt_l29_charger_type
      to: "ac"
  condition:
    - condition: state
      entity_id: person.jimmy
      state: "home"
    - condition: state
      entity_id: binary_sensor.garagelas
      state: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        title: "Garagelåset"
        message: "Garaget är inte låst"
        data:
          notification_icon: "mdi:garage-lock"
#
- alias: "leaving_home_garagelas"
  id: "Inte hemma - Garaget ej låst"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: person.jimmy
      from: "home"
    - platform: state
      entity_id: person.hanna
      from: "home"
  condition:
    - not:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: home"
    - condition: state
      entity_id: binary_sensor.garagelas
      state: "on"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Garaget är inte låst"
        data:
          notification_icon: "mdi:garage-lock"
#
- alias: "Svullo dead notify Android"
  id: "Notifiering att Svullo har dött"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.svullo
      to: "down"
  action:
    - service: notify.mobile_app_clt_l29
      data:
        message: "Svullo har dött"
        data:
          notification_icon: "mdi:nas"
#
- alias: "Qtorr dead notify Android"
  id: "Notifiering att Qtorr har dött"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.qtorrent
      to: "down"
  action:
    - service: notify.mobile_app_clt_l29
      data:
        message: "Qtorr har dött"
        data:
          notification_icon: "mdi:monitor-arrow-down"
#
- alias: "fas1_dead"
  id: "Fas1 har dött"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_energy_meter_gen5_electric_consumption_v_1
      below: 50
      for: "00:02:00"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Ström har gått på fas 1"
        data:
          ttl: 0
          priority: high
          channel: alarm_stream
          notification_icon: "mdi:lightning-bolt"
#
- alias: "fas2_dead"
  id: "Fas2 har dött"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_energy_meter_gen5_electric_consumption_v_2
      below: 50
      for: "00:02:00"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Ström har gått på fas 2"
        data:
          ttl: 0
          priority: high
          channel: alarm_stream
          notification_icon: "mdi:lightning-bolt"
#
- alias: "fas3_dead"
  id: "Fas3 har dött"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_energy_meter_gen5_electric_consumption_v_3
      below: 50
      for: "00:02:00"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Ström har gått på fas 3"
        data:
          ttl: 0
          priority: high
          channel: alarm_stream
          notification_icon: "mdi:lightning-bolt"
#
- alias: "fas1_overcharge"
  id: "Fas1 är överbelastad"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_energy_meter_gen5_electric_consumption_w_1
      above: 3600
      for: "00:05:00"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Fas 1 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_1') }}"
        data:
          notification_icon: "mdi:meter-electric"
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 1 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_1') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 1 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_1') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 1 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_1') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 1 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_1') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
#
- alias: "fas2_overcharge"
  id: "Fas2 är överbelastad"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_energy_meter_gen5_electric_consumption_w_2
      above: 3600
      for: "00:05:00"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Fas 2 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_2') }}"
        data:
          notification_icon: "mdi:meter-electric"
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 2 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_2') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 2 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_2') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 2 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_2') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 2 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_2') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
#
- alias: "fas3_overcharge"
  id: "Fas3 är överbelastad"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_energy_meter_gen5_electric_consumption_w_3
      above: 3600
      for: "00:05:00"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "Fas 3 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_3') }}"
        data:
          notification_icon: "mdi:meter-electric"
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 3 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_3') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 3 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_3') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 3 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_3') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: a10341
        text: "Fas 3 har varit överbelastad i över 5min: {{ states('sensor.home_energy_meter_gen5_electric_consumption_w_3') }}"
        category: notifications
        sound: energy
        sound_repeat: 1
#
- alias: "soppan okq8 maxi notify Android"
  id: "Notifiering att soppan är billig OKQ8 Maxi"
  initial_state: true
  mode: single
  trigger:
    - platform: template
      value_template: "{{ states('sensor.billig_soppa_maxi_borlange_14d') > states('sensor.95_okq8_borlange_vid_maxi') }}"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.95_okq8_borlange_vid_maxi
          state: "unavailable"
        - condition: state
          entity_id: sensor.billig_soppa_maxi_borlange_14d
          state: "unavailable"
  action:
    - service: notify.mobile_app_clt_l29
      data:
        title: "Soppan är billig: OKQ8 blge maxi"
        message: "Passa på att tanka: {{ states('sensor.95_okq8_borlange_vid_maxi') }}"
        data:
          notification_icon: "mdi:gas-station"
#
- alias: "soppan okq8 ingarvet notify Android"
  id: "Notifiering att soppan är billig OKQ8 ingarvet"
  initial_state: true
  mode: single
  trigger:
    - platform: template
      value_template: "{{ states('sensor.billig_soppa_ingarvet_14d') > states('sensor.95_okq8_falun_ingarvet') }}"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.95_okq8_falun_ingarvet
          state: "unavailable"
        - condition: state
          entity_id: sensor.billig_soppa_ingarvet_14d
          state: "unavailable"
  action:
    - service: notify.mobile_app_hanna
      data:
        title: "Soppan är billig: OKQ8 Falun ingarvet"
        message: "Passa på att tanka: {{ states('sensor.95_okq8_falun_ingarvet') }}"
        data:
          notification_icon: "mdi:gas-station"
#
- alias: "adguard_filter_off"
  id: "adguard filter avstängt"
  initial_state: true
  mode: single
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    - condition: state
      entity_id: switch.adguard_filtering
      state: "off"
  action:
    - service: notify.hanna_jimmy
      data:
        message: "AdGuard filter avstängt"
        data:
          notification_icon: "mdi:dns"
#
- alias: "Notifierng_Gardena_unavailabe"
  id: "Notif_gardena_unavailable"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.gardena_smart_system_connection
      to: "off"
      for:
        minutes: 5
  action:
    - service: notify.mobile_app_clt_l29
      data:
        title: "Gardena offline"
        message: "Kolla om omstart behövs"
        data:
          notification_icon: "mdi:mower"
#
