############################################
##
## Software automations
##
############################################



############################################
##
## All
##
############################################

#
#
#
- alias: "hacs update notify Android"
  id: "Notifiering att hacs har uppdatering"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "20:40:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: notify.mobile_app_clt_l29
      data: 
        message: "HACS har tillgänglig uppdatering"
#
#- alias: "zigbee2mqtt_restart"
#  id: "Omstart av Zigbee2mqtt"
#  initial_state: true
#  mode: single
#  trigger:
#    - platform: time
#      at: "03:00:00"
#  condition:
#    - condition: time
#      weekday:
#        - thu
#  action:
#    - service: hassio.addon_restart
#      data: 
#        addon: 45df7312_zigbee2mqtt
#
