


#
- alias: "trash_pickup_Android_discord"
  id: "Sophämtning Android och Discord"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "17:00:00"
  condition:
    - condition: time
      weekday:
      - mon
    - "{{ now().isocalendar()[1] % 2 == 1 }}"
  action:
    - service: notify.hanna_jimmy
      data: 
        message: "Sophämtning imorgon, dags att köra fram tunnorna"
        data:
          notification_icon: "mdi:delete-empty"
    - service: notify.discord
      data: 
        message: "Sophämtning imorgon, dags att köra fram tunnorna"
        target: !secret discord_message
#
- alias: "trash_pickup_lametric"
  id: "Sophämtning LaMetric"
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "19:00:00"
    - platform: time
      at: "20:00:00"
  condition:
    - condition: time
      weekday:
      - mon
    - "{{ now().isocalendar()[1] % 2 == 1 }}"
  action:
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: i16307
        text: "Sophämtning imorgon, är tunnorna framme?"
        category: notifications
        sound: open_door
        sound_repeat: 1
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: i16307
        text: "Sophämtning imorgon, är tunnorna framme?"
        category: notifications
        sound: open_door
        sound_repeat: 1
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: i16307
        text: "Sophämtning imorgon, är tunnorna framme?"
        category: notifications
        sound: open_door
        sound_repeat: 1
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 2
        icon: i16307
        text: "Sophämtning imorgon, är tunnorna framme?"
        category: notifications
        sound: open_door
        sound_repeat: 1
#
