#
#
#

- alias: "notification_washer_done"
  id: "Notifiering när tävttmaskinerna är klara"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.washers_onoff
      from: "on"
      to: "off"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jimmy
          state: "home"
        - condition: state
          entity_id: person.hanna
          state: "home"
        - condition: state
          entity_id: input_boolean.visitors
          state: "on"
  action:
    - service: shell_command.lmvardagsrum_washers_ready
    - service: shell_command.lmsovrum_washers_ready
    - service: shell_command.lmmatsal_washers_ready
    #  - service: notify.lametric
    #    data:
    #      message: "Tvättmaskiner är klara!"
    #      data:
    #        icon: 'a9482'
    #        icon_type: 'none'
    #        sound: 'notification'
    #        priority: 'warning'
    #        cycles: 2
    - service: notify.hanna_jimmy
      data:
        title: "Tvättmaskiner klara"
        message: "Häng tvätten!"
    - delay: "00:01:00"
    #  - service: notify.lametric
    #    data:
    #      message: "Tvättmaskiner är klara!"
    #      data:
    #        icon: 'a9482'
    #        icon_type: 'none'
    #        sound: 'notification2'
    #        priority: 'warning'
    #        cycles: 2
    - service: shell_command.lmvardagsrum_washers_ready
    - service: shell_command.lmsovrum_washers_ready
    - service: shell_command.lmmatsal_washers_ready
    - service: switch.turn_off
      target:
        entity_id: switch.washers
    - service: climate.turn_on
      target:
        entity_id: climate.jimmy_s_smart_ac
#
- alias: "washer_done_boolean"
  id: "Tvättmaskinerna är klara Boolean"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.washers_watts
      below: 3
      for:
        minutes: 5
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.washers_onoff
#
- alias: "washer_started_boolean"
  id: "Tvättmaskinerna är startade Boolean"
  initial_state: true
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.washers_watts
      above: 3
      for:
        seconds: 30
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.washers_onoff
    - service: climate.turn_off
      target:
        entity_id: climate.jimmy_s_smart_ac
#
