#
#
#
- alias: "notification_water_leak_dish"
  id: "Notifiering vattenläcka under diskho"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.water_dish
      to: "on"
  action:
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: notify.hanna_jimmy
      data:
        title: "Vattenläcka!"
        message: "Vattenläcka under diskho"
        data:
          notification_icon: "mdi:pipe-leak"
    - delay: "00:00:10"
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - delay: "00:00:10"
    - service: rest_command.lmhobbyrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmmatsal_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmsovrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
    - service: rest_command.lmvardagsrum_post_notification_sound
      data:
        priority: warning
        cycles: 3
        icon: a12989
        text: "Vattenläcka under diskho!"
        category: notifications
        sound: negative5
        sound_repeat: 2
#
